#!/usr/bin/bash

set -eu

git checkout main

git pull origin main

branch=$(cat deckfm_update_and_run)

git checkout $branch

git pull origin $branch

mkdir -p build

cd build

cmake ..

make -j8

cd ..

$(pwd)/deckfm.sh
