#!/usr/bin/bash

set -eu

git checkout main

git pull origin main

git fetch

branch=$(cat update_branch_dev)

git checkout $branch

git pull origin $branch

mkdir -p build

cd build

cmake ..

make -j8

cd ..

LD_LIBRARY_PATH=$(pwd) ./build/deckfm
