version: '3.8'

services:
  builder:
    image: ghcr.io/zhulik/holo-dev
    volumes:
      - ./:/mnt
    user: ${BUILDER_UID}:${BUILDER_GID}
    command: |
      bash -c "set -eu &&
        cd /mnt &&
        mkdir -p build.holo &&
        cd build.holo &&
        cmake .. &&
        make -j`nproc`"
