version: '3.8'

services:
  builder:
    image: ghcr.io/zhulik/holo-dev
    volumes:
      - ./:/mnt
    command: |
      bash -c "cd /mnt &&
        mkdir -p build.holo &&
        cd build.holo &&
        cmake .. &&
        make -j$(nproc)"