name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_image:
    name: Build DeckFM
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Build DeckFM
        run: UID="$(id -u)" GID="$(id -g)" docker-compose up
